import { Inter } from 'next/font/google'
import './globals.css'
import Image from 'next/image'
import Script from 'next/script'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Script
      src="https://kit.fontawesome.com/c53c92435c.js"
      crossorigin="anonymous"
    ></Script>
      <body className={inter.className}><div className="hidden bg-white2 drop-shadow md:flex content-center p-2 gap-8 px-6">
        <div className="flex items-center gap-3">
          <i className="fa-solid fa-phone text-black1" />
          <p className="font-plus-jakarta">+421 905 249 998</p>
        </div>
        <div className="flex items-center gap-3">
          <i className="fa-solid fa-envelope text-black1" />
          <p className="font-plus-jakarta">patras@patras.sk</p>
        </div>
        <div className="ml-auto flex flex-row gap-4">
          <p className="font-plus-jakarta">Kontakty</p>
          <p className="font-plus-jakarta">O nas</p>
        </div>
      </div> {children} 
      <footer className="flex items-center m-4 justify-center md:m-8">
        <div className="flex items-center gap-5 md:gap-12">
         <div className="relative hidden md:h-[95px] w-48 md:block">
         <Image
            src="/IMG/logo.png"
            alt="patras.sk"
            fill
          />
         </div>
          <p className="font-plus-jakarta text-[8px] md:text-h7">
            patras@patras.sk
          </p>
          <p className="font-plus-jakarta text-[8px] md:text-h7">
            +421 905 249 998
          </p>
          <p className="font-plus-jakarta flex text-[8px] md:text-h7">
            Mlynska 34 976 Selce
          </p>
          <a href="">
            <p className="font-plus-jakarta text-[8px] md:text-h7">
              Obchodne podmienky
            </p>
          </a>
          <a href="">
            <p className="font-plus-jakarta text-[8px] md:text-h7">
              Podmienky reklamacie
            </p>
          </a>
        </div>
      </footer></body>

      

    </html>
  )
}

